### ISSUE TITLE
Choosing Device

### ISSUE THREAD

**Issue by davidbp** [JuliaGPU/GPUArrays.jl#48] opened 2017-08-12 16:21 UTC
Is there a way to choose the device where we will allocate the arrays? (and perform comutations)

I can see what seems to be the current device
```julia
julia> CLBackend.current_context()
CLContext: AMD Radeon HD - FirePro D300 Compute Engine
```

I see though that there are several possible devices (in this case too many there are only 2 GPUs in my machine not 3).
```julia
julia> CLBackend.all_contexts()
3-element Array{GPUArrays.CLBackend.CLContext,1}:
 CLContext: AMD Radeon HD - FirePro D300 Compute Engine
 CLContext: AMD Radeon HD - FirePro D300 Compute Engine
 CLContext: AMD Radeon HD - FirePro D300 Compute Engine
```

In ArrayFire for example,  `ArrayFire.AFInfo()` gives you device infor and it can be used to select a device.

```julia
julia> ArrayFire.AFInfo()
ArrayFire v3.3.2 (OpenCL, 64-bit Mac OSX, build f65dd97)
[0] APPLE   : AMD Radeon HD - FirePro D300 Compute Engine, 2048 MB
-1- APPLE   : AMD Radeon HD - FirePro D300 Compute Engine, 2048 MB
```

What are the most differences where GPUArrays might differ from ArrayFire?

**Comment by SimonDanisch** [comment] 2017-08-12 16:33
duplicate of https://github.com/JuliaGPU/GPUArrays.jl/issues/38

**Comment by davidbp** [comment] 2017-08-12 16:41
cool it´s beeing solved. you can close it

**Closed** 2017-08-12 16:42 UTC
